package InterficieGrafica;

public class ConcreteDecorators extends javax.swing.JPanel {

	private final Controlador c;
	
	private static int i = 0, j= 0, k=0;
	
    /**
     * Creates new form ConcreteDecorators
     */
    public ConcreteDecorators() {
        initComponents();
        c = new Controlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LambdaBtn = new javax.swing.JButton();
        EncryptionBtn = new javax.swing.JButton();
        FireWallBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

         LambdaBtn.setFont(new java.awt.Font("Source Code Pro", 0, 18)); // NOI18N
        LambdaBtn.setText("Lambda");
        LambdaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LambdaBtnActionPerformed(evt);
            }
        });

        EncryptionBtn.setFont(new java.awt.Font("Source Code Pro", 0, 18)); // NOI18N
        EncryptionBtn.setText("Encryption");
        EncryptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptionBtnActionPerformed(evt);
            }
        });

        FireWallBtn.setFont(new java.awt.Font("Source Code Pro", 0, 18)); // NOI18N
        FireWallBtn.setText("FireWall");
        FireWallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FireWallBtnActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LambdaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EncryptionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FireWallBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FireWallBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LambdaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(EncryptionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        
                                       
    private void FireWallBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	String name = "HelloWorldFireWall "+(++i);
        String tipo = "HelloWorldFireWall";
        c.crearActor(name, tipo, 0, "");
    }       

    private void LambdaBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	String name = "HelloWorldLambda "+(++j);
        String tipo = "HelloWorldLambda";
        c.crearActor(name, tipo, 0, "");
    }   
    
    private void EncryptionBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	String name = "HelloWorldEncryption "+(++k);
        String tipo = "HelloWorldEncryption";
        c.crearActor(name, tipo, 0, "");
    }  
                                         


    // Variables declaration - do not modify                     
    private javax.swing.JButton EncryptionBtn;
    private javax.swing.JButton FireWallBtn;
    private javax.swing.JButton LambdaBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
