package InterficieGrafica;
import java.awt.BorderLayout;

/**
 * 
 * @author Marc Fonseca y Joel Lacambra
 *
 */

public class Decorator extends javax.swing.JPanel {

    /**
     * Creates new form AddInsult
     */
    private String insult;
    
    private static final long serialVersionUID = 1L;

    private final Controlador c;
    private static int j= 0;
    
    /**
     * Constructor de Decorator
     */
    public Decorator() {
        initComponents();
        c = new Controlador();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addInsultPanel = new javax.swing.JPanel();
        DecoratorBtn1 = new javax.swing.JLabel();
        SiBtn = new javax.swing.JButton();
        NoBtn = new javax.swing.JButton();
        ConcreteDecoratorsPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(434, 161));

        addInsultPanel.setBackground(new java.awt.Color(204, 204, 255));

        DecoratorBtn1.setFont(new java.awt.Font("Source Code Pro Black", 1, 24)); // NOI18N
        DecoratorBtn1.setText("Decorator");

        SiBtn.setFont(new java.awt.Font("Source Code Pro", 0, 18)); // NOI18N
        SiBtn.setText("Sí");
        SiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiBtnActionPerformed(evt);
            }
        });

        NoBtn.setFont(new java.awt.Font("Source Code Pro", 0, 18)); // NOI18N
        NoBtn.setText("No");
        NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBtnActionPerformed(evt);
            }
        });

        ConcreteDecoratorsPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout ConcreteDecoratorsPanelLayout = new javax.swing.GroupLayout(ConcreteDecoratorsPanel);
        ConcreteDecoratorsPanel.setLayout(ConcreteDecoratorsPanelLayout);
        ConcreteDecoratorsPanelLayout.setHorizontalGroup(
            ConcreteDecoratorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        ConcreteDecoratorsPanelLayout.setVerticalGroup(
            ConcreteDecoratorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout addInsultPanelLayout = new javax.swing.GroupLayout(addInsultPanel);
        addInsultPanel.setLayout(addInsultPanelLayout);
        addInsultPanelLayout.setHorizontalGroup(
            addInsultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addInsultPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(addInsultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addInsultPanelLayout.createSequentialGroup()
                        .addComponent(SiBtn)
                        .addGap(18, 18, 18)
                        .addComponent(NoBtn))
                    .addComponent(DecoratorBtn1)
                    .addComponent(ConcreteDecoratorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        addInsultPanelLayout.setVerticalGroup(
            addInsultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addInsultPanelLayout.createSequentialGroup()
                .addComponent(DecoratorBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addInsultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(ConcreteDecoratorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addInsultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addInsultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        
    
    /**
     * Metodo que se activa al presionar "si", crea un HelloWorld con Decorator
     * @param evt
     */
    private void SiBtnActionPerformed(java.awt.event.ActionEvent evt) {                                      
    	ConcreteDecorators cd = new ConcreteDecorators();
        cd.setSize(147, 276);
        cd.setLocation(0, 0); 
       
       
        ConcreteDecoratorsPanel.removeAll();
        ConcreteDecoratorsPanel.add(cd, BorderLayout.CENTER);
        ConcreteDecoratorsPanel.revalidate();
        ConcreteDecoratorsPanel.repaint();
    }                                     

    /**
     * Metodo que se activa al presionar "no", crea un HelloWord normal
     * @param evt
     */
    private void NoBtnActionPerformed(java.awt.event.ActionEvent evt) {                                      
    	ConcreteDecoratorsPanel.removeAll();
        ConcreteDecoratorsPanel.revalidate();
        ConcreteDecoratorsPanel.repaint();
        
        String name = "HelloWorld "+(++j);
        String tipo = "HelloWorld";
        c.crearActor(name, tipo, 0, "");
    }                                    
    
    // Variables declaration - do not modify                     
    private javax.swing.JPanel ConcreteDecoratorsPanel;
    private javax.swing.JLabel DecoratorBtn1;
    private javax.swing.JButton NoBtn;
    private javax.swing.JButton SiBtn;
    private javax.swing.JPanel addInsultPanel;
    // End of variables declaration                    
}

